const fs = require('fs');
let file = fs.readFileSync('src/contexts/ContentContext.tsx', 'utf8');

const targetContent = '<p>Traditional Kerala bridal attire is historically associated with pure yellow gold, but a magnificent renaissance is underway. Modern brides are beautifully fusing heritage gold silhouettes with GIA and IGI certified diamonds, creating unforgettable antique diamond jewellery masterpieces.</p><p>Whether for Hindu, Christian, or Muslim ceremonies, classic designs like the Mullamottu Mala (jasmine bud necklace) and Palakka Mala are being reimagined with brilliant-cut diamonds and vivid emerald accents. Heavy haraams, Lakshmi necklaces, and jhumkas set with uncut Polki diamonds offer a grand, royal aesthetic that perfectly complements the traditional Kasavu saree.</p><p>At Kirthi Diamonds, we craft bespoke bridal suites that respect regional traditions while elevating them through hand-selected stones, ensuring every bride carries forward a radiant heritage.</p>';

const faqContent = `<h3>Are real antique Kerala diamond pieces available for purchase?</h3><p>Genuine 75-year-old antique pieces are very rarely available retail — most stay in families. What is available is antique-style reproduction using contemporary certified diamonds, and heritage-design work inspired by traditional motifs. At Kirthi Diamonds we specialise in both.</p><h3>What is the difference between Hindu, Christian, and Muslim Kerala bridal jewellery?</h3><p>Hindu Kerala bridal jewellery layers traditional named pieces (Mullamottu Mala, Palakka Mala, Lakshmi Haram, Nagapadam) in yellow gold with diamond accents. Christian Kerala brides typically choose white-gold or yellow-gold settings with diamond and pearl detailing in cascading designs. Muslim Kerala brides traditionally wear matched diamond sets featuring chokers, matha pattis, kada bangles, and jhumkas with intricate patterning.</p><h3>Can my family heirloom be reset into a modern piece while preserving the antique feel?</h3><p>Yes — this is one of the most common bespoke commissions we receive. The original gold and stones are preserved; the design is reinterpreted to suit modern daily wear while keeping the heritage motif. We document the original piece before disassembly and provide the reset piece with full certification of the diamonds.</p><h3>What is the typical budget for a complete Kerala bridal diamond set?</h3><p>A traditional Kerala bridal set typically ranges from ₹4 lakh to ₹40 lakh and above, depending on diamond weight, gold weight, and number of pieces. A full Kirthi Diamonds bridal package — necklace set, earrings, bangles, and central solitaire — commonly sits in the ₹8–25 lakh range for high-quality certified work.</p><h3>Where can I view antique-style Kerala wedding diamond jewellery in person?</h3><p>At Kirthi Diamonds Kochi (34/572 By Pass Road, Palarivattom, Mon–Sat 10am–7:30pm) and Calicut (61/11508A, opposite Federal Bank, Puthiyara, Mon–Sat 9:30am–7:30pm). Heritage consultations for bridal commissions are by appointment.</p>`;

file = file.replace(targetContent, targetContent + faqContent);

fs.writeFileSync('src/contexts/ContentContext.tsx', file);
